### ISSUE TITLE
Mekanism syntax(?) spelling mistake

### ISSUE THREAD

**Issue by Quarris** [jaredlll08/CraftTweaker-Documentation#24]
Under the Mekanism tabs as far as I can see all of them mention the name of imports as "mod.mekanism..." instead of "mods.mekanism...".

**Comment by jaredlll08** [comment]
have you tested the docs? I know that mekanism actually uses "mod." in some places, so test the docs before, just to make sure they are right / wrong

**Comment by Quarris** [comment]
"mod." gave me an error so I tried "mods." and it worked.

**Comment by kindlich** [comment]
I'll look into it
