### ISSUE TITLE
Two instances of incorrect documentation as of version 4.0.10 of CraftTweaker.

### ISSUE THREAD

**Issue by The-Arcanian** [jaredlll08/CraftTweaker-Documentation#32]
Casting as an ore dictionary entry is `as IOreDictEntry` not `as IOreDictionary`. [Problem file.](https://github.com/jaredlll08/CraftTweaker-Documentation/blob/master/docs/Vanilla/Variable_Types/Variable_Types.md) This problem caused me to submit [this](https://github.com/jaredlll08/CraftTweaker/issues/374).

`.reuse()` no longer exists and users are supposed to use `.transformDamage(0)`. [Problem file.](https://github.com/jaredlll08/CraftTweaker-Documentation/blob/master/docs/Vanilla/Variable_Types/IIngredient.md) Had to comb through the change history to find this after about an hour or two of trying to find what was wrong with my scripts.

**Comment by jaredlll08** [comment]
These have been fixed.
